datas: 
  '1':
    '2': 1
    '6': 3
    '7': 2
    '8': 2
  '2':
    '1': 1
    '3': 2
    '7': 1
  '3':
    '2': 2
    '4': 3
    '7': 2
  '4':
    '3': 3
    '5': 3
    '7': 2
  '5':
    '4': 3
    '6': 4
    '8': 1
  '6':
    '1': 3
    '5': 4
    '8': 5
  '7':
    '1': 2
    '2': 1
    '3': 2
    '4': 2
    '8': 1
  '8':
    '1': 2
    '5': 1
    '6': 5
    '7': 1

start: '1'
end: '4'